name: publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    name: Build and publish to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Publish site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          cname: tomragonneau.com
